// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIRW63tzL6JhaMJgk_mRn22xTBeGiEjNE',
    appId: '1:720667706724:web:c7dd5d2fb0f127ff71a671',
    messagingSenderId: '720667706724',
    projectId: 'laundrybrew-4bf26',
    authDomain: 'laundrybrew-4bf26.firebaseapp.com',
    storageBucket: 'laundrybrew-4bf26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy7g_LUe24kyWZ0UY4TfbacD4EhYu_DNQ',
    appId: '1:720667706724:android:7fe53e93a20a5c4a71a671',
    messagingSenderId: '720667706724',
    projectId: 'laundrybrew-4bf26',
    storageBucket: 'laundrybrew-4bf26.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0EZhd8G8yTCrggoy6c8R5jWkuz_aGMH8',
    appId: '1:720667706724:ios:e0034bcb272036d671a671',
    messagingSenderId: '720667706724',
    projectId: 'laundrybrew-4bf26',
    storageBucket: 'laundrybrew-4bf26.firebasestorage.app',
    iosBundleId: 'com.laundrybrew.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0EZhd8G8yTCrggoy6c8R5jWkuz_aGMH8',
    appId: '1:720667706724:ios:e0034bcb272036d671a671',
    messagingSenderId: '720667706724',
    projectId: 'laundrybrew-4bf26',
    storageBucket: 'laundrybrew-4bf26.firebasestorage.app',
    iosBundleId: 'com.laundrybrew.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIRW63tzL6JhaMJgk_mRn22xTBeGiEjNE',
    appId: '1:720667706724:web:c7dd5d2fb0f127ff71a671',
    messagingSenderId: '720667706724',
    projectId: 'laundrybrew-4bf26',
    authDomain: 'laundrybrew-4bf26.firebaseapp.com',
    storageBucket: 'laundrybrew-4bf26.firebasestorage.app',
  );
}
